### ISSUE TITLE
Divide product tabs from related products

### ISSUE THREAD

**Issue by Pescao** [jameskoster/woocommerce-product-details-customiser#1]
Hi! I want to customize my shop. Actually, i want to display product tabs (description, attributes, reviews etc.) under price - to the right of product image. When i put this code into product summary DIV:

do_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_product_data_tabs', 10);

tabs are shown, but also related product are shown too :( But i want to put 'related products' AFTER product summary. Here's the screenshot of what i have now: http://www.foto-me.ru/v.php?id=81c1adc29d0dbe6c171ee4e6d6d2684d 

Please help my issue.

**Comment by jameskoster** [comment]
Hey, not sure why you've posted this here. This is for reporting bugs in the Product Details Customiser plugin :-P

You should use `add_action()` not `do_action()`. That should be added to your themes functions.php file instead.

Then use `remove_action()` to remove the default elements.

**Comment by Pescao** [comment]
Actually i could not find private messages there, nor your contact. Thanks
for help
24.10.2013 15:36 ÐÏÌØÚÏ×ÁÔÅÌØ "James Koster" notifications@github.com
ÎÁÐÉÓÁÌ:
