### ISSUE TITLE
Missing argument 3 for avia_woocommerce

### ISSUE THREAD

**Issue by fasace** [jameskoster/woocommerce-product-details-customiser#10]
Hi, I have a page displaying the product having this error. You can like a developer to say what is the reason and how can I resolve it. I used a plugin to customize the images of the goods, but it did not help. http://joxi.ru/D2Pg4QLSdZd4Xm http://joxi.ru/4AkLveqHM8MBdr I read somewhere that after you upgrade WordPress 4.7.1 difficulties with the payment details, I can advise to correct this bug.

Warning: Missing argument 3 for avia_woocommerce_gallery_thumbnail_description(), called in /var/www/moiaxwzy/data/www/sale-management.ru/wp-includes/class-wp-hook.php on line 298 and defined in /var/www/moiaxwzy/data/www/sale-management.ru/wp-content/themes/enfold/config-woocommerce/config.php on line 1360

Warning: Missing argument 3 for avia_woocommerce_gallery_thumbnail_description(), called in /var/www/moiaxwzy/data/www/sale-management.ru/wp-includes/class-wp-hook.php on line 298 and defined in /var/www/moiaxwzy/data/www/sale-management.ru/wp-content/themes/enfold/config-woocommerce/config.php on line 1360

I used thumbnails but it did not help
thank you, will be able to write the answer

**Comment by jameskoster** [comment]
`/wp-content/themes/enfold/config-woocommerce/config.php`

Looks like the problem is coming from your theme. I'd advise speaking with the author. Good luck!
