### ISSUE TITLE
Incompatibility with WC2.1 Mobile Responsiveness?

### ISSUE THREAD

**Issue by MadSpaniard** [jameskoster/woocommerce-product-details-customiser#2]
It seems that the setting "Related Products / Upsells Columns" may not play well with the new mobile responsiveness in WC2.1.  

The default setting is 2 columns.  However, if you change it to 4, the full front-end (e.g. on a PC or Laptop browser) adjusts accordingly and nicely, however if you view it on an iPhone, then it inadvertently displays the Related Products/Upsell products within the product page in extremely narrow columns (seemingly attempting to accommodate 4 columns).

Perhaps the CSS for this plugin could check (e.g. @media queries) for mobile devices and deliberately ignore any column settings other than the default 2 columns for mobile devices while still retaining the column setting on full-browser devices)?

Thank you in advance.

**Comment by jameskoster** [comment]
Fixed in 0.2.0 :-)
