### ISSUE TITLE
"Related Products / Upsells Columns" Governs #Items not #Columns

### ISSUE THREAD

**Issue by MadSpaniard** [jameskoster/woocommerce-product-details-customiser#3]
I just tested the latest master that includes the enhancements for WC2.1 + Mobile Responsiveness on WC2-1 RC1.  The mobile responsiveness on an iphone now displays nicely in 2 columns, regardless what "Related Products / Upsells Columns" is set to.

However, on a full browser (e.g. PC/Tablet) this setting now governs the # of Related Products/Upsells to be displayed, rather than the # of columns that the items should be displayed in.  Meaning, if it is set to 3, then exactly 3 products will be shown in 2 columns, rather than the default # of Related items shown in 3 columns.  Further, the 1st row will show 1 item, then the 2nd row will show 2 items.

On a mobile browser, the setting also now governs the # of Related/Upsell items shown (they will be displayed in 2 columns as noted above on mobile devices).

Previously, this setting governed the # of columns the related/upsell items would be arranged in, rather than the # of items to be displayed.  I believe that behavior would be the desired one for this particular setting.

BTW, including a second and separate setting for "Number of Related / Upsells Products" in this plugin would also be a nice enhancement, allowing for even more flexibility.

**Comment by jameskoster** [comment]
I think it makes sense for the number of related products to match the number of columns. I've added a filter so that this can be tweaked though via your child theme.
