### ISSUE TITLE
Number of Products per page not working in WC 2.1

### ISSUE THREAD

**Issue by chirag-v** [jameskoster/woocommerce-product-details-customiser#4]
After update all products appear on shop page.

**Comment by chirag-v** [comment]
Updating to WooCommerce 2.1

**Comment by jameskoster** [comment]
There is no products per page option in this plugin? Did you mean the archive customiser?

**Comment by chirag-v** [comment]
Oh yes I posted in the wrong plugin. This is happening for archive customiser. Will post it there.
