### ISSUE TITLE
Per Page issue

### ISSUE THREAD

**Issue by billras** [jameskoster/woocommerce-product-details-customiser#7]
Hi!

I ran into an issue when using the Per Page option -- if the user is on a page that wouldn't exist when the Per Page option is changed (eg. page 3 is viewed when 10 per page is set, then Per Page is changed to 20 per page), a Page Not Found error occurred.

To work around this, I added an action URL to the form opening tag at line 305:

```
<form class="woocommerce-ordering" method="post" action="<?php echo get_permalink( woocommerce_get_page_id( 'shop' ) ); ?>">
```

This should ensure that the user is taken to the first page of shop results when they change the Per Page option, rather than encountering a page error.

Worth adding to the plugin?

Bill

**Comment by jameskoster** [comment]
Hey, yeah this is definitely worth adding, wanna send a PR? I should be able to merge and release this weekend.

**Comment by billras** [comment]
Woops, just realized this is for a different plugin ... I was referring to **WooCommerce Product Archive Customiser** ...

After a more tinkering, I noticed that the action URL treatment needed a little more work so it would a) include the active querystring (if there was one from, say, the sorting dropdown), b) differentiate between shop archive, product archive and tag archive pages based on the section the user was viewing.

Handling this required a few additional changes -- here's the modified function that starts at line 292 of the **WooCommerce Product Archive Customiser** plugin:

```
            // Per Page Dropdown
            function woocommerce_pac_show_product_perpage() {
                $per_page = get_option( 'wc_pac_products_per_page' );

                if ( isset( $_REQUEST['per_page'] ) ) {
                    $woo_per_page = $_REQUEST['per_page'];
                } elseif ( ! isset( $_REQUEST['per_page'] ) && isset( $_COOKIE['per_page'] ) ) {
                    $woo_per_page = $_COOKIE['per_page'];
                } else {
                    $woo_per_page = $per_page;
                }

                // set action URL
                if ( is_shop() ) {
                    $url = get_permalink( woocommerce_get_page_id( 'shop' ) );
                } elseif ( is_product_category() ) {
                    global $wp_query;
                    $cat = $wp_query->get_queried_object();
                    $url = get_term_link( $cat );
                } elseif ( is_product_tag() ) {
                    global $wp_query;
                    $tag = $wp_query->get_queried_object();
                    $url = get_term_link( $tag );
                }

                // add querystring to URL if set
                if ( $_SERVER['QUERY_STRING'] != '' ) {
                    $url .= '?' . $_SERVER['QUERY_STRING'];
                }

                ?>
                <form class="woocommerce-ordering" method="post" action="<?php echo $url; ?>">
                    <select name="per_page" class="per_page" onchange="this.form.submit()">
                        <?php
                            $x = 1;
                            while ( $x <= 5 ) {
                                $value      = $per_page * $x;
                                $selected   = selected( $woo_per_page, $value, false );
                                $label      = __( "{$value} per page", 'woocommerce-product-archive-customiser' );
                                echo "<option value='{$value}' {$selected}>{$label}</option>";
                                $x++;
                            }
                        ?>
                    </select>
                </form>
                <?php
            }
```

It may require more testing / tinkering to ensure it doesn't unintentionally pooch other functionality or plugins.

Sorry about attaching this to the wrong plugin repository ... ack. :P

**Comment by jameskoster** [comment]
Heh, I didn't even notice this was opened on the wrong repo xD

If you could send a PR to the correct one I'll test this some time. It's funny, that feature was actually added by someone else so I'll need to look at it closely. 

Struggling for time a bit though so I'm not sure when I'll be able to do so.

**Comment by billras** [comment]
:D

I don't use GitHub much so finding my way around. I think I just submitted
a PR ... lol.

Bill :D
