### ISSUE TITLE
Plugin settings lost randomly

### ISSUE THREAD

**Issue by seanvfs** [jameskoster/woocommerce-product-details-customiser#9]
On multiple sites I've experienced a complete loss of the plugin settings.  This results in product detail content and other elements controlled by this plugin to not be displayed on the front end of the site.  I haven't consistently reproduced the problem but have experienced it on multiple production sites.

I wonder if the way that the settings are being stored could be getting cleared out with a WooCommerce or WordPress update?

**Comment by jameskoster** [comment]
They're stored in the WooCommerce settings so it's possible. Not sure without looking into it further though which isn't something I have time to do just now.
